/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adrian' at '30.04.15 19:30' with Gradle 2.3
 *
 * @author adrian, @date 30.04.15 19:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
